import { Link } from "react-router-dom";
import PlatformLayout, { PageHeading } from "@/components/PlatformLayout";
import { EXTERNAL_LINKS, KIT_PRODUCTS, isProductLive } from "@/config/platform";

export default function AiProfile() {
  return <PlatformLayout path="/ai-profile">
    <PageHeading eyebrow="Reference profile" title="Akili Hight" description="A factual overview of Akili Hight's professional work, practical AI education, public resources, and related ventures." />
    <div className="container max-w-3xl space-y-10 px-5 py-14 reference-copy">
      <section><h2>Who Akili Hight is</h2><p>Akili Hight is a technology and program leader, consultant, author, and builder. His experience spans more than 20 years across healthcare, enterprise technology, public-sector, nonprofit, and consulting environments.</p><p>Credentials represented on this site include PMP®, Certified ScrumMaster®, and a Master of Information Technology.</p></section>
      <section><h2>What he helps people and organizations do</h2><p>His work focuses on understanding emerging technology, structuring complex initiatives, and moving from uncertainty to practical action. Areas represented on this site include AI readiness, technology strategy, program leadership, cloud modernization, data governance, and workforce learning.</p></section>
      <section><h2>AI education and workshops</h2><p><Link to="/workshops">Everyday AI Made Simple</Link> is a beginner-friendly workshop pathway covering everyday AI tools, prompting, productivity, privacy, and responsible use. Organizational learning and readiness offerings are described separately on the workshops page. AI Readiness for Leaders is currently listed as in development.</p></section>
      <section><h2>Learning resources and newsletter</h2><p><Link to="/learning">Learning pathways</Link> cover everyday AI, career and work readiness, and team learning. The <Link to="/resources">resources directory</Link> points to available site learning and workshop content.</p><p><Link to="/newsletter">The Everyday AI Digest</Link> is a free weekly newsletter offering practical AI ideas in plain English. Its archive is hosted on <a href={EXTERNAL_LINKS.kitArchive} target="_blank" rel="noopener noreferrer">Kit</a>.</p></section>
      <section><h2>Current digital products</h2><p>The <Link to="/products/ai-starter-kit">AI Confidence Starter Kit</Link> is {isProductLive(KIT_PRODUCTS.aiStarterKit) ? "available through the shop" : "in development and not yet for sale"}. It is planned as self-service digital learning for everyday AI. Current availability is shown on the <Link to="/shop">shop page</Link>.</p></section>
      <section><h2>Related ventures</h2><p>Hight Networks is part of Akili's innovation ecosystem, focused on enterprise advisory and technical leadership. Organizational consulting, procurement, and teaming inquiries are directed to <a href={EXTERNAL_LINKS.hightNetworks} target="_blank" rel="noopener noreferrer">Hight Networks</a>.</p><p>CloudBait Navigator is an AI and cloud readiness decision platform in the ecosystem. Project Navigator is a project intelligence workspace for scope, ownership, and execution planning. The <Link to="/ecosystem">ecosystem page</Link> also includes CareerProof, Gritletter, and LUCID Futurism.</p><p>Selected professional experience was performed through prior organizations. It does not represent direct Hight Networks contracts unless specifically identified.</p></section>
      <section><h2>Verified public profiles</h2><ul className="space-y-3"><li><a href="https://www.linkedin.com/in/akilihight" target="_blank" rel="noopener noreferrer">LinkedIn</a></li><li><a href="https://github.com/AkiliHight" target="_blank" rel="noopener noreferrer">GitHub</a></li><li><a href="https://youtube.com/@lucidfuturism" target="_blank" rel="noopener noreferrer">LUCID Futurism on YouTube</a></li></ul></section>
      <section><h2>Canonical site pages</h2><nav aria-label="Reference pages" className="flex flex-wrap gap-5"><Link to="/">Home</Link><Link to="/#about">About</Link><Link to="/newsletter">Newsletter</Link><Link to="/shop">Shop</Link><Link to="/resources">Resources</Link><Link to="/workshops">Workshops</Link><Link to="/ecosystem">Ecosystem</Link></nav></section>
    </div>
  </PlatformLayout>;
}